# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'f:\Documents\Programmation\PublicProject\patcher_NonaryGame_PC_official\mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(916, 267)
        MainWindow.setMinimumSize(QtCore.QSize(916, 267))
        MainWindow.setMaximumSize(QtCore.QSize(916, 267))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/ressource/DreamteamLogo.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_browse = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_browse.setGeometry(QtCore.QRect(810, 10, 101, 31))
        self.pushButton_browse.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.pushButton_browse.setObjectName("pushButton_browse")
        self.pushButton_process = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_process.setGeometry(QtCore.QRect(340, 110, 111, 61))
        self.pushButton_process.setMaximumSize(QtCore.QSize(16777215, 16777211))
        self.pushButton_process.setObjectName("pushButton_process")
        self.lineEdit_gamePath = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_gamePath.setGeometry(QtCore.QRect(10, 10, 791, 31))
        self.lineEdit_gamePath.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_gamePath.setObjectName("lineEdit_gamePath")
        self.groupBox_choicePatch = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_choicePatch.setGeometry(QtCore.QRect(20, 70, 301, 161))
        self.groupBox_choicePatch.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.groupBox_choicePatch.setObjectName("groupBox_choicePatch")
        self.checkBox_999 = QtWidgets.QCheckBox(self.groupBox_choicePatch)
        self.checkBox_999.setGeometry(QtCore.QRect(30, 70, 251, 31))
        self.checkBox_999.setChecked(True)
        self.checkBox_999.setObjectName("checkBox_999")
        self.checkBox_Launcher = QtWidgets.QCheckBox(self.groupBox_choicePatch)
        self.checkBox_Launcher.setGeometry(QtCore.QRect(30, 30, 121, 31))
        self.checkBox_Launcher.setChecked(True)
        self.checkBox_Launcher.setObjectName("checkBox_Launcher")
        self.checkBox_VLR = QtWidgets.QCheckBox(self.groupBox_choicePatch)
        self.checkBox_VLR.setGeometry(QtCore.QRect(30, 110, 221, 31))
        self.checkBox_VLR.setChecked(True)
        self.checkBox_VLR.setObjectName("checkBox_VLR")
        self.textEdit_log = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_log.setGeometry(QtCore.QRect(490, 70, 401, 161))
        self.textEdit_log.setAcceptDrops(False)
        self.textEdit_log.setReadOnly(True)
        self.textEdit_log.setObjectName("textEdit_log")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "DreamTeamTrad - Patcheur automatique pour Zero Escape: The Nonary Games"))
        self.pushButton_browse.setText(_translate("MainWindow", "Rechercher"))
        self.pushButton_process.setText(_translate("MainWindow", "Patcher"))
        self.lineEdit_gamePath.setPlaceholderText(_translate("MainWindow", "Indiquer le chemin du dossier du jeu"))
        self.groupBox_choicePatch.setTitle(_translate("MainWindow", "Choix des patchs"))
        self.checkBox_999.setText(_translate("MainWindow", "9 Hours, 9 Doors, 9 Persons"))
        self.checkBox_Launcher.setText(_translate("MainWindow", "Launcher"))
        self.checkBox_VLR.setText(_translate("MainWindow", "Virtue\'s Last Reward"))
import ressource_rc
